In [2]:
import pandas as pd

df = pd.read_csv("../fraudTrain.csv")

print(df.shape)
print(df.columns.tolist())
print(df["is_fraud"].value_counts())

(1296675, 23)
['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud']
is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [3]:
!pip install mlflow xgboost imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting mlflow
  Downloading mlflow-3.13.0-py3-none-any.whl.metadata (49 kB)
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: imbalanced-learn in d:\programdata\anaconda3\lib\site-packages (0.14.0)
Collecting mlflow-skinny==3.13.0 (from mlflow)
  Downloading mlflow_skinny-3.13.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.13.0 (from mlflow)
  Downloading mlflow_tracing-3.13.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (3.1.2)
Requirement already satisfied: aiohttp<4 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (3.13.2)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: cryptography<49,>=43.0.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (46.0.3)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.0.3-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: matplotlib<4 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (3.10.6)
Requirement already satisfied: numpy<3 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (2.3.5)
Requirement already satisfied: pandas<3 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<25,>=4.0.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (21.0.0)
Requirement already satisfied: scikit-learn<2 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (1.7.2)
Requirement already satisfied: scipy<2 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow) (2.0.43)
Collecting waitress<4 (from mlflow)
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: cachetools<8,>=5.0.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (8.2.1)
Requirement already satisfied: cloudpickle<4 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.1)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading databricks_sdk-0.117.0-py3-none-any.whl.metadata (43 kB)
Collecting fastapi<1 (from mlflow-skinny==3.13.0->mlflow)
  Downloading fastapi-0.136.3-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.45)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (8.7.0)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading opentelemetry_proto-1.42.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging<27 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (5.29.3)
Requirement already satisfied: pydantic<3,>=2.0.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (1.1.0)
Requirement already satisfied: pyyaml<7,>=5.1 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.13.0->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting starlette<2 (from mlflow-skinny==3.13.0->mlflow)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in d:\programdata\anaconda3\lib\site-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Collecting uvicorn<1 (from mlflow-skinny==3.13.0->mlflow)
  Downloading uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in d:\programdata\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.22.0)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Using cached mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: colorama in d:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.13.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in d:\programdata\anaconda3\lib\site-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow)
  Downloading google_auth-2.54.0-py3-none-any.whl.metadata (5.6 kB)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: urllib3<3,>=1.26 in d:\programdata\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.5.0)
Requirement already satisfied: pywin32>=304 in d:\programdata\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\programdata\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.13.0->mlflow)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: blinker>=1.9.0 in d:\programdata\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in d:\programdata\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in d:\programdata\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in d:\programdata\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in d:\programdata\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\programdata\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\programdata\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\programdata\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in d:\programdata\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in d:\programdata\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\programdata\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.2.5)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow)
  Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pytz>=2020.1 in d:\programdata\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\programdata\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in d:\programdata\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\programdata\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in d:\programdata\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in d:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in d:\programdata\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\programdata\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: greenlet>=1 in d:\programdata\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.2.4)
Requirement already satisfied: anyio<5,>=3.6.2 in d:\programdata\anaconda3\lib\site-packages (from starlette<2->mlflow-skinny==3.13.0->mlflow) (4.10.0)
Requirement already satisfied: sniffio>=1.1 in d:\programdata\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.13.0->mlflow) (1.3.0)
Requirement already satisfied: h11>=0.8 in d:\programdata\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.13.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in d:\programdata\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (2.23)
Requirement already satisfied: wcwidth in d:\programdata\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.13)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in d:\programdata\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.1)
Downloading mlflow-3.13.0-py3-none-any.whl (10.8 MB)
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.8 MB 3.1 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/10.8 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/10.8 MB 4.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.8 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/10.8 MB 4.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/10.8 MB 4.5 MB/s eta 0:00:02
   ----------------------- ---------------- 6.3/10.8 MB 4.6 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.8 MB 4.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.8 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.8 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/10.8 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 10.5/10.8 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 10.8/10.8 MB 4.2 MB/s  0:00:02
Downloading mlflow_skinny-3.13.0-py3-none-any.whl (3.4 MB)
   ---------------------------------------- 0.0/3.4 MB ? eta -:--:--
   --------- ------------------------------ 0.8/3.4 MB 4.5 MB/s eta 0:00:01
   --------------------- ------------------ 1.8/3.4 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 3.1/3.4 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 3.4/3.4 MB 5.2 MB/s  0:00:00
Downloading mlflow_tracing-3.13.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------- -------------- 1.0/1.7 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 7.4 MB/s  0:00:00
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading databricks_sdk-0.117.0-py3-none-any.whl (936 kB)
   ---------------------------------------- 0.0/936.9 kB ? eta -:--:--
   ---------------------------------------- 936.9/936.9 kB 5.5 MB/s  0:00:00
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Downloading fastapi-0.136.3-py3-none-any.whl (117 kB)
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading google_auth-2.54.0-py3-none-any.whl (249 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading huey-3.0.3-py3-none-any.whl (94 kB)
Downloading opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
Downloading opentelemetry_proto-1.42.1-py3-none-any.whl (71 kB)
Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
Using cached sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
Downloading uvicorn-0.49.0-py3-none-any.whl (71 kB)
Downloading waitress-3.0.2-py3-none-any.whl (56 kB)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Installing collected packages: huey, waitress, sqlparse, protobuf, prettytable, opentelemetry-api, Mako, graphql-core, annotated-doc, xgboost, uvicorn, starlette, opentelemetry-semantic-conventions, opentelemetry-proto, graphql-relay, docker, alembic, skops, opentelemetry-sdk, graphene, google-auth, Flask-CORS, fastapi, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow

   ----------------------------------------  0/27 [huey]
   ----------------------------------------  0/27 [huey]
   ----------------------------------------  0/27 [huey]
   - --------------------------------------  1/27 [waitress]
   - --------------------------------------  1/27 [waitress]
   -- -------------------------------------  2/27 [sqlparse]
   -- -------------------------------------  2/27 [sqlparse]
   ---- -----------------------------------  3/27 [protobuf]
   ---- -----------------------------------  3/27 [protobuf]
   ---- -----------------------------------  3/27 [protobuf]
   ---- -----------------------------------  3/27 [protobuf]
   ---- -----------------------------------  3/27 [protobuf]
   ---- -----------------------------------  3/27 [protobuf]
   ----- ----------------------------------  4/27 [prettytable]
   ------- --------------------------------  5/27 [opentelemetry-api]
   ------- --------------------------------  5/27 [opentelemetry-api]
   -------- -------------------------------  6/27 [Mako]
   -------- -------------------------------  6/27 [Mako]
   -------- -------------------------------  6/27 [Mako]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ---------- -----------------------------  7/27 [graphql-core]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   ------------- --------------------------  9/27 [xgboost]
   -------------- ------------------------- 10/27 [uvicorn]
   -------------- ------------------------- 10/27 [uvicorn]
   -------------- ------------------------- 10/27 [uvicorn]
   ---------------- ----------------------- 11/27 [starlette]
   ---------------- ----------------------- 11/27 [starlette]
   ---------------- ----------------------- 11/27 [starlette]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]
   -------------- ------------------ 12/27 [opentelemetry-semantic-conventions]

  WARNING: The script huey_consumer.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script waitress-serve.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sqlformat.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mako-render.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script uvicorn.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script alembic.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script fastapi.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'C:\Users\HP\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    accuracy_score
)

from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier

import mlflow
import mlflow.sklearn
import mlflow.xgboost

from mlflow import MlflowClient

ModuleNotFoundError: No module named 'imblearn'

In [5]:
import sys

!{sys.executable} -m pip install imbalanced-learn xgboost mlflow

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: xgboost in C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages (3.2.0)
Requirement already satisfied: mlflow in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (2.10.2)
Requirement already satisfied: numpy<3,>=1.25.2 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.11.4 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from imbalanced-learn) (3.6.0)
Requirement already satisfied: click<9,>=7.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (8.3.3)
Requirement already satisfied: cloudpickle<4 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.1.2)
Requirement already satisfied: entrypoints<1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (0.4)
Requirement already satisfied: gitpython<4,>=2.1.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.1.50)
Requirement already satisfied: pyyaml<7,>=5.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (6.0.3)
Requirement already satisfied: protobuf<5,>=3.12.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (4.25.9)
Requirement already satisfied: pytz<2024 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (2023.4)
Requirement already satisfied: requests<3,>=2.17.3 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (2.33.1)
Requirement already satisfied: packaging<24 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (23.2)
Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (7.2.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (0.5.5)
Requirement already satisfied: alembic!=1.10.0,<2 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (1.18.4)
Requirement already satisfied: docker<8,>=4.0.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: Flask<4 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: pandas<3 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: querystring-parser<2 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (1.2.4)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (2.0.49)
Requirement already satisfied: pyarrow<16,>=4.0.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (15.0.2)
Requirement already satisfied: markdown<4,>=3.3 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.10.2)
Requirement already satisfied: matplotlib<4 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.10.9)
Requirement already satisfied: waitress<3 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (2.1.2)
Requirement already satisfied: Jinja2<4,>=3.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from mlflow) (3.1.6)
Requirement already satisfied: Mako in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from alembic!=1.10.0,<2->mlflow) (4.15.0)
Requirement already satisfied: colorama in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from click<9,>=7.0->mlflow) (0.4.6)
Requirement already satisfied: pywin32>=304 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from docker<8,>=4.0.0->mlflow) (2.7.0)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from gitpython<4,>=2.1.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=0.5 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow) (3.23.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from matplotlib<4->mlflow) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: six in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from querystring-parser<2->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from requests<3,>=2.17.3->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from requests<3,>=2.17.3->mlflow) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from requests<3,>=2.17.3->mlflow) (2026.4.22)
Requirement already satisfied: greenlet>=1 in C:\Users\HP\AppData\Roaming\Python\Python311\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.0)
Downloading imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Downloading sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.2 sklearn-compat-0.1.6

In [6]:
import imblearn
import xgboost
import mlflow

print(imblearn.__version__)
print(xgboost.__version__)
print(mlflow.__version__)

0.14.2
3.2.0
2.10.2

In [2]:
df = pd.read_csv("../fraudTrain.csv")

print(df.shape)

df.head()

NameError: name 'pd' is not defined

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    accuracy_score
)

from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier

import mlflow
import mlflow.sklearn
import mlflow.xgboost

from mlflow import MlflowClient

In [4]:
df = pd.read_csv("../fraudTrain.csv")

# Sample 200,000 rows
df = df.sample(
    n=200000,
    random_state=42
)

print(df.shape)

df.head()

(200000, 23)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
1045211,1045211,2020-03-09 15:09:26,577588686219,fraud_Towne LLC,misc_pos,194.51,James,Strickland,M,25454 Leonard Lake,...,40.6153,-79.4545,972,Public relations account executive,1997-10-23,fff87d4340ef756a592eac652493cf6b,1362841766,40.420453,-78.865012,0
547406,547406,2019-08-22 15:49:01,30376238035123,fraud_Friesen Ltd,health_fitness,52.32,Cynthia,Davis,F,7177 Steven Forges,...,42.8250,-124.4409,217,Retail merchandiser,1928-10-01,d0ad335af432f35578eea01d639b3621,1345650541,42.758860,-123.636337,0
110142,110142,2019-03-04 01:34:16,4658490815480264,fraud_Mohr Inc,shopping_pos,6.53,Tara,Richards,F,4879 Cristina Station,...,39.9636,-79.7853,184,Systems developer,1945-11-04,87f26e3ea33f4ff4c7a8bad2c7f48686,1330824856,40.475159,-78.898190,0
1285953,1285953,2020-06-16 20:04:38,3514897282719543,fraud_Gaylord-Powlowski,home,7.33,Steven,Faulkner,M,841 Cheryl Centers Suite 115,...,42.9580,-77.3083,10717,Cytogeneticist,1952-10-13,9c34015321c0fa2ae6fd20f9359d1d3e,1371413078,43.767506,-76.542384,0
271705,271705,2019-05-14 05:54:48,6011381817520024,"fraud_Christiansen, Goyette and Schamberger",gas_transport,64.29,Kristen,Allen,F,8619 Lisa Manors Apt. 871,...,41.6423,-104.1974,635,Product/process development scientist,1973-07-13,198437c05676f485e9be04449c664475,1336974888,41.040392,-104.092324,0

In [5]:
print(df["is_fraud"].value_counts())

print("\nPercentage Distribution")

print(
    df["is_fraud"].value_counts(normalize=True) * 100
)

is_fraud
0    198811
1      1189
Name: count, dtype: int64

Percentage Distribution
is_fraud
0    99.4055
1     0.5945
Name: proportion, dtype: float64

In [6]:
drop_cols = [
    "Unnamed: 0",
    "trans_date_trans_time",
    "first",
    "last",
    "street",
    "city",
    "state",
    "job",
    "dob",
    "trans_num"
]

df = df.drop(columns=drop_cols)

print(df.shape)

(200000, 13)

In [7]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

df.head()

,cc_num,merchant,category,amt,gender,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
1045211,577588686219,629,9,194.51,1,15686,40.6153,-79.4545,972,1362841766,40.420453,-78.865012,0
547406,30376238035123,180,5,52.32,0,97476,42.8250,-124.4409,217,1345650541,42.758860,-123.636337,0
110142,4658490815480264,429,12,6.53,0,15449,39.9636,-79.7853,184,1330824856,40.475159,-78.898190,0
1285953,3514897282719543,187,6,7.33,1,14425,42.9580,-77.3083,10717,1371413078,43.767506,-76.542384,0
271705,6011381817520024,92,2,64.29,0,82221,41.6423,-104.1974,635,1336974888,41.040392,-104.092324,0

In [8]:
X = df.drop("is_fraud", axis=1)

y = df["is_fraud"]

print(X.shape)
print(y.shape)

(200000, 12)
(200000,)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

Train Shape: (140000, 12)
Test Shape: (60000, 12)

In [10]:
print("Before SMOTE")
print(y_train.value_counts())

Before SMOTE
is_fraud
0    139168
1       832
Name: count, dtype: int64

In [12]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

In [13]:
print("After SMOTE")
print(y_train_smote.value_counts())

After SMOTE
is_fraud
0    139168
1    139168
Name: count, dtype: int64

In [14]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

experiment_name = "Anomaly Detection MLflow"

mlflow.set_experiment(experiment_name)

print("MLflow Connected")

2026/06/13 16:05:44 INFO mlflow.tracking.fluent: Experiment with name 'Anomaly Detection MLflow' does not exist. Creating a new experiment.

MLflow Connected

In [15]:
def log_metrics(y_true, y_pred):

    report = classification_report(
        y_true,
        y_pred,
        output_dict=True
    )

    accuracy = accuracy_score(y_true, y_pred)

    recall_class_0 = report["0"]["recall"]
    recall_class_1 = report["1"]["recall"]

    f1_macro = report["macro avg"]["f1-score"]

    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("recall_class_0", recall_class_0)
    mlflow.log_metric("recall_class_1", recall_class_1)
    mlflow.log_metric("f1_score_macro", f1_macro)

    return recall_class_1, f1_macro

In [16]:
with mlflow.start_run(
    run_name="Logistic Regression"
):

    model = LogisticRegression(
        C=1,
        solver="liblinear",
        random_state=42
    )

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mlflow.log_param("C", 1)
    mlflow.log_param("solver", "liblinear")

    log_metrics(y_test, predictions)

    mlflow.sklearn.log_model(
        model,
        "model"
    )

print("Logistic Regression Done")

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Logistic Regression Done

In [17]:
with mlflow.start_run(
    run_name="Random Forest"
):

    model = RandomForestClassifier(
        n_estimators=30,
        max_depth=3,
        random_state=42
    )

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mlflow.log_param(
        "n_estimators",
        30
    )

    mlflow.log_param(
        "max_depth",
        3
    )

    log_metrics(y_test, predictions)

    mlflow.sklearn.log_model(
        model,
        "model"
    )

print("Random Forest Done")

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Random Forest Done

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:15: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

In [18]:
with mlflow.start_run(
    run_name="XGBoost"
):

    model = XGBClassifier(
        eval_metric="logloss",
        random_state=42
    )

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mlflow.log_param(
        "eval_metric",
        "logloss"
    )

    log_metrics(y_test, predictions)

    mlflow.xgboost.log_model(
        model,
        "model"
    )

print("XGBoost Done")

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\xgboost\sklearn.py:1116: UserWarning: [16:14:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\c_api\c_api.cc:1573: Saving model in the UBJSON format as default.  You can use a file extension: `json` or `ubj` to choose between formats.
  self.get_booster().save_model(fname)

XGBoost Done

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:15: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

In [19]:
with mlflow.start_run(
    run_name="XGBoost With SMOTE"
):

    model = XGBClassifier(
        eval_metric="logloss",
        random_state=42
    )

    model.fit(
        X_train_smote,
        y_train_smote
    )

    predictions = model.predict(X_test)

    mlflow.log_param(
        "eval_metric",
        "logloss"
    )

    mlflow.log_param(
        "sampling",
        "SMOTE"
    )

    log_metrics(y_test, predictions)

    mlflow.xgboost.log_model(
        model,
        "model"
    )

print("XGBoost With SMOTE Done")

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\xgboost\sklearn.py:1116: UserWarning: [16:16:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\c_api\c_api.cc:1573: Saving model in the UBJSON format as default.  You can use a file extension: `json` or `ubj` to choose between formats.
  self.get_booster().save_model(fname)

XGBoost With SMOTE Done

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:15: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

In [20]:
client = MlflowClient()

experiment = client.get_experiment_by_name(
    experiment_name
)

runs_df = mlflow.search_runs(
    experiment_ids=[experiment.experiment_id]
)

runs_df = runs_df.sort_values(
    by=[
        "metrics.recall_class_1",
        "metrics.f1_score_macro"
    ],
    ascending=False
)

runs_df[
    [
        "run_id",
        "tags.mlflow.runName",
        "metrics.accuracy",
        "metrics.recall_class_1",
        "metrics.f1_score_macro"
    ]
]

,run_id,tags.mlflow.runName,metrics.accuracy,metrics.recall_class_1,metrics.f1_score_macro
0,a63b995a06db4ab99dd7499f27990b00,XGBoost With SMOTE,0.99110,0.750700,0.748222
1,aecb323d703040889365a3740976c91f,XGBoost,0.99630,0.593838,0.827243
2,a54fa7142cd9414da6876fa311b857d1,Random Forest,0.99405,0.000000,0.498508
3,1abd5f4a02c240f3a9b062b6ae50011c,Logistic Regression,0.99405,0.000000,0.498508

In [21]:
best_run_id = "a63b995a06db4ab99dd7499f27990b00"

model_uri = f"runs:/{best_run_id}/model"

registered_model = mlflow.register_model(
    model_uri=model_uri,
    name="anomaly-detector-xgb-smote"
)

print("Version:", registered_model.version)

Successfully registered model 'anomaly-detector-xgb-smote'.
2026/06/13 16:36:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: anomaly-detector-xgb-smote, version 1

Version: 1

Created version '1' of model 'anomaly-detector-xgb-smote'.

In [22]:
client = MlflowClient()

client.set_registered_model_alias(
    name="anomaly-detector-xgb-smote",
    alias="challenger",
    version=1
)

print("Challenger Alias Assigned")

TypeError: bad argument type for built-in operation

In [23]:
print(type(registered_model.version))
print(registered_model.version)

<class 'str'>
1

In [24]:
client = MlflowClient()

client.set_registered_model_alias(
    name="anomaly-detector-xgb-smote",
    alias="challenger",
    version="1"
)

print("Challenger Alias Assigned")

Challenger Alias Assigned

In [25]:
client.copy_model_version(
    src_model_uri="models:/anomaly-detector-xgb-smote/1",
    dst_name="anomaly-detection-prod"
)

print("Production Model Created")

Production Model Created

In [26]:
versions = client.search_model_versions(
    "name='anomaly-detection-prod'"
)

for v in versions:
    print("Version:", v.version)

Version: 1

In [27]:
client.set_registered_model_alias(
    name="anomaly-detection-prod",
    alias="champion",
    version="1"
)

print("Champion Alias Assigned")

Champion Alias Assigned

In [28]:
production_model = mlflow.pyfunc.load_model(
    "models:/anomaly-detection-prod@champion"
)

sample_data = X_test.head(10)

predictions = production_model.predict(sample_data)

print(predictions)

[0 0 0 0 0 0 0 0 0 0]

C:\Users\HP\.conda\envs\mlflow_env\Lib\site-packages\xgboost\sklearn.py:1125: UserWarning: [16:50:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\c_api\c_api.cc:1509: Unknown file format: `xgb`. Using UBJSON (`ubj`) as a guess.
  self.get_booster().load_model(fname)